### ISSUE TITLE
Make background flash on goal

### ISSUE THREAD

**Issue by martinoj2009** [martinoj2009/JH7#1]
Need the background to flash when there's a goal. Goal is detected in Box.java on line 104.

**Comment by martinoj2009** [comment]
Will do audio instead. Added audio to the game already.

**Comment by mgebremedhin** [comment]
The “hit” and “point” .wav audio files are not being implemented on my end. The files exist and are within the file directory of my Java Project within Eclipse. Are you having any issues with them?

**Comment by mgebremedhin** [comment]
They consistently have Eclipse throwing NullPointerExceptions whenever a point is scored or a paddle makes contact with the ball.

**Comment by mgebremedhin** [comment]
Verified audio files and appropriate calls for them are working as intended.
